name: Geneve Reyes
markdown: redcarpet
pygments: true
github: https://www.github.com/geneve
about: Name's Gene, located in San Francisco. Currently dabbling in object-oriented technologies for junior software development.
urls:
    - text: github
      url: https://github.com/geneve
    - text: linkedin
      url: https://www.linkedin.com/in/genevereyes
    - text: resume
      url: img/reyesgeneve.pdf
    - text: email
      url: mailto:genevereyes@gmail.com