name: Geneve Reyes
markdown: redcarpet
pygments: true
github: https://www.github.com/geneve
about: 					Call me Gene! I am currently a senior undergraduate in San Francisco. This is my landing page!
urls:
    - text: linkedin
      url: https://www.linkedin.com/in/genevereyes
    - text: github
      url: https://github.com/geneve
    - text: email
      url: mailto:genevereyes@gmail.com