name: Geneve Reyes
markdown: redcarpet
pygments: true
github: https://www.github.com/geneve
about: Welcome! My name is Gene. Currently a student in San Francisco, dabbling in object-oriented technologies.
urls:
    - text: github
      url: https://github.com/geneve
    - text: linkedin
      url: https://www.linkedin.com/in/genevereyes
    - text: resume
      url: /img/reyesgeneve.pdf
    - text: email
      url: mailto:genevereyes@gmail.com