name: Geneve Reyes
markdown: redcarpet
pygments: true
github: https://www.github.com/geneve
about: Call me Gene! I am currently a senior undergraduate in San Francisco. Currently dabbling in object-oriented technologies for information delivery through Business Intelligence / Web Development.

urls:
    - text: linkedin
      url: https://www.linkedin.com/in/genevereyes
    - text: github
      url: https://github.com/geneve
    - text: email
      url: mailto:genevereyes@gmail.com
    - text: database design
      url: http://genevereyes.com/blog/2014/06/25/building-database-project.html