name: Gene Reyes
markdown: redcarpet
pygments: true
github: https://www.github.com/geneve
about: 	Gene is a Data Analyst at a major utilities company in the US. He uses this web site to blog about his adventures in data analytics. 
urls:
    - text: linkedin
      url: https://www.linkedin.com/in/genevereyes
    - text: github
      url: https://github.com/geneve
    - text: email
      url: mailto:genevereyes@gmail.com